version: 2.1
jobs:
  go-build:
    working_directory: ~/repo

    docker:
      - image: circleci/golang:1.12.5-stretch

    steps:
      - checkout
      - run:
          name: update
          command: sudo apt update
      - run:
          name: run unit test
          command: go test ~/repo/...
      - run:
          name: build go
          command: go build -o test-go main.go
      - persist_to_workspace:
          root: ~/repo
          paths:
            - test-go
workflows:
  version: 2
  run_all:
    jobs:
      - go-build