version: 2
jobs:
  # go test
  go-test:
    working_directory: ~/repo

    docker:
      - image: circleci/golang:1.12.5-stretch
    steps:
      - checkout
      - run:
          name: update
          command: sudo apt update
      - run:
          name: cp env
          command: cp ~/repo/env/circleci.env ~/repo/.env
      - run:
          name: run unit test
          command: ENV_FILE=env/circleci.env go test $(go list ~/repo/... | grep -v "sample")
  #      - run:
  #          name: build go
  #          command: go build -o locust main.go
  #      - persist_to_workspace:
  #          root: ~/repo
  #          paths:
  #            - locust
  # ruby e2eテスト
  ruby-e2e:
    working_directory: ~/repo

    docker:
      - image: circleci/ruby:latest
      - image: rodolpheche/wiremock
    steps:
      - checkout
      #      - attach_workspace:
      #          at: ~/repo
      - run:
          name: update
          command: sudo apt update
      - run:
          name: cp env
          command: cp ~/repo/env/circleci.env ~/repo/.env
      - run:
          name: install bundler
          command: gem install bundler
      - run:
          name: bundle install
          command: cd ~/repo/test && bundle install --path vendor/bundle
      - run:
          name: run e2e test
          command: cd ~/repo/test && ENV_FILE=~/repo/.env bundle exec rspec
  #      - persist_to_workspace:
  #          root: ~/repo
  #          paths:
  #            - infrastructure/
  #            - locust
  #            - env
  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6-jessie-node-browsers
    steps:
      #      - attach_workspace:
      #          at: ~/repo

      - checkout

      - setup_remote_docker

      - run:
          name: install aws
          command: pip3 install awscli --upgrade --user
      - run:
          name: Set environment variables
          command: |
            echo "export AWS_ACCESS_KEY_ID=${STAGING_AWS_ACCESS_KEY_ID}" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=${STAGING_AWS_SECRET_ACCESS_KEY}" >> $BASH_ENV
            echo "export PATH=~/.local/bin:$PATH" >> $BASH_ENV
      - run:
          name: docker build
          command: |
            cd ~/repo
            $(aws ecr get-login --no-include-email --region ap-northeast-1)
            docker build -t ride-locust .
            docker tag ride-locust:latest 356315504566.dkr.ecr.ap-northeast-1.amazonaws.com/test-app:$CIRCLE_SHA1
            docker push 356315504566.dkr.ecr.ap-northeast-1.amazonaws.com/test-app:$CIRCLE_SHA1
#      - run:
#          name: ecs deploy
#          command: ecs-deploy -n test-service -c test -t 240 -i 356315504566.dkr.ecr.ap-northeast-1.amazonaws.com/test-app:$CIRCLE_SHA1
#          no_output_timeout: 20m
workflows:
  version: 2
  run_all:
    jobs:
      - go-test
      - ruby-e2e:
          requires:
            - go-test
      - deploy:
          #      - deploy
          requires:
            - go-test
            - ruby-e2e
#          filters:
#            branches:
#              only: develop