version: 2.1
jobs:
  sshconfirm:
#    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6-jessie-node-browsers
      - image: adoptopenjdk/openjdk11

    steps:
#      - run:
#          name: Install rsync
#          command: sudo apt install -y rsync
#      - run:
#          name: Install Ansible
#          command: sudo pip install ansible
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "42:f2:8d:b3:01:8c:e0:6b:05:93:91:d9:91:be:d3:b1"
#      - run:
#          name: pre install java
#          command: sudo apt install openjdk-9-jdk
#      - run:
#          name: confirm java
#          command: which java && java --help
#      - run:
#          name: confirm alternatives
#          command: which alternatives
      - run:
          name: get jdk
          command: wget https://github.com/AdoptOpenJDK/openjdk9-binaries/releases/download/jdk-9.0.4%2B11/OpenJDK9U-jdk_x64_linux_hotspot_9.0.4_11.tar.gz
      - run:
          name: tar
          command: tar xvzf OpenJDK9U-jdk_x64_linux_hotspot_9.0.4_11.tar.gz
      - run:
          name: jdk
          command: ls && echo $PWD && ls $PWD/jdk-9.0.4+11/bin
      - run:
          name: set PATH
          command: echo 'export PATH=$PWD/jdk-9.0.4+11/bin:$PATH' >> $BASH_ENV
      - run:
          name: confirm PATH
          command: echo $PATH
      - run:
          name: confirm java
          command: which java
      - run:
          name: confirm java 2
          command: java -version
      - run:
          name: confirm docker
          command: which docker
      - run:
          name: confirm systemctl
          command: which systemctl
      - run:
          name: confirm service
          command: which service
      - run:
          name: start docker
          command: systemctl start docker
      - run:
          name: pre install mock server
          command: wget http://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/2.17.0/wiremock-standalone-2.17.0.jar
      - run:
          name: exe jar
          command: ls && java -jar wiremock-standalone-2.17.0.jar
      - run:
          name: ls
          command: ls -la ~
      - run:
          name: ls .ssh
          command: ls -la ~/.ssh
      - run:
          name: cat id_rsa
          command: cat ~/.ssh/id_rsa
      - run:
          name: ls project
          command: ls -la ~/project
      - run:
          name: Deploy with Ansible
          command: cd ~/project/ansible && ansible-playbook -i locust.ini site.yml
#      - run:
#          name: ssh
#          command: ssh -i ~/.ssh/id_a91c81e5ade3cd813d890aa6009d9b508e902b24 ec2-user@3.113.25.250
workflows:
  version: 2
  run_all:
    jobs:
      - sshconfirm