version: 2.1
jobs:
  sshconfirm:
    working_directory: ~/repo

    docker:
      - image: circleci/python:3.6-jessie-node-browsers

    steps:
      - add_ssh_keys:
          fingerprints:
            - 9a:3e:43:63:96:74:90:7b:86:c9:2f:f1:13:8a:f4:2f
      - run:
          name: ls
          command: ls -la ~
      - run:
          name: ls 2
          command: ls -la ~/repo
workflows:
  version: 2
  run_all:
    jobs:
      - sshconfirm