version: 2.1
jobs:
  sshconfirm:
#    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6-jessie-node-browsers
      - image: circleci/openjdk:9.0.1

    steps:
      - run:
          name: Install rsync
          command: sudo apt install -y rsync
      - run:
          name: Install Ansible
          command: sudo pip install ansible
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "42:f2:8d:b3:01:8c:e0:6b:05:93:91:d9:91:be:d3:b1"
      - run:
          name: pre install mock server
          command: wget -P ~ http://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/2.17.0/wiremock-standalone-2.17.0.jar
      - run:
          name: ls hoge
          command: ls ~
      - run:
          name: exe jar
          command: java -jar ~/wiremock-standalone-2.12.0.jar
      - run:
          name: ls
          command: ls -la ~
      - run:
          name: ls .ssh
          command: ls -la ~/.ssh
      - run:
          name: cat id_rsa
          command: cat ~/.ssh/id_rsa
      - run:
          name: ls project
          command: ls -la ~/project
      - run:
          name: Deploy with Ansible
          command: cd ~/project/ansible && ansible-playbook -i locust.ini site.yml
#      - run:
#          name: ssh
#          command: ssh -i ~/.ssh/id_a91c81e5ade3cd813d890aa6009d9b508e902b24 ec2-user@3.113.25.250
workflows:
  version: 2
  run_all:
    jobs:
      - sshconfirm